kind: Service
apiVersion: v1
metadata:
  name: car-game-service
  namespace: car-game
spec:
  selector:
    app: car-game
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
