apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-game-deployment
  namespace: car-game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: car-game
  template:
    metadata:
      labels:
        app: car-game
    spec:
      containers:
        - name: car-game
          image: nitin0412/car-racing-game:v1
          ports:
            - containerPort: 80
