apiVersion: v1
kind: Service
metadata:
  name: car-game-service
  namespace: car-game
spec:
  selector:
    app: car-game
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
